dist: xenial
language: python
cache: pip
notifications:
  email: false
sudo: true

python:
  - "3.8.1"
install:
  - pip install black==19.10b0
script:
  - python -m compileall .
  - black --check -N `git ls-files "*.py"`


