dist: xenial
language: python
cache: pip
notifications:
  email: false
sudo: true

python:
  - "3.7"
install:
  - pip install black==18.9b0
script:
  - python -m compileall .
  - black --check `git ls-files "*.py"`


